gitconfig: 
  - name: github
    url: https://github.com/

  - name: fd
    url: git://anongit.freedesktop.org/git/

  - name: gnome
    url: https://git.gnome.org/

  - name: kernel
    url: git://git.kernel.org/pub/scm/linux/kernel/git/

  - name: fedora
    url: git://git.fedorahosted.org/

  - name: fedorapkgs
    url: git://pkgs.fedoraproject.org/

